export default {

  PROGRESS_START: 'PROGRESS_START',
  PROGRESS_STOP: 'PROGRESS_STOP',
  // Login Types
  LOGIN_OTP_REQUEST: "LOGIN_OTP_REQUEST",
  LOGIN_OTP_SUCCESS: "LOGIN_OTP_SUCCESS",
  LOGIN_OTP_FAILURE: "LOGIN_OTP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  
  LOGIN_RESEND_OTP_REQUEST: "LOGIN_RESEND_OTP_REQUEST",
  LOGIN_RESEND_OTP_SUCCESS: "LOGIN_RESEND_OTP_SUCCESS",
  LOGIN_RESEND_OTP_FAILURE: "LOGIN_RESEND_OTP_FAILURE",

  // Logout type
  LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",

  // Sign-up Types
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

  // Forget Password
  POST_FORGET_PASSWORD_REQUEST: "POST_FORGET_PASSWORD_REQUEST",
  POST_FORGET_PASSWORD_SUCCESS: "POST_FORGET_PASSWORD_SUCCESS",
  POST_FORGET_PASSWORD_FAILURE: "POST_FORGET_PASSWORD_FAILURE",

  // Update Forget Password
  POST_UPDATE_FORGET_PASSWORD_REQUEST: "POST_UPDATE_FORGET_PASSWORD_REQUEST",
  POST_UPDATE_FORGET_PASSWORD_SUCCESS: "POST_UPDATE_FORGET_PASSWORD_SUCCESS",
  POST_UPDATE_FORGET_PASSWORD_FAILURE: "POST_UPDATE_FORGET_PASSWORD_FAILURE",

  RESET_FORGET_PASSWORD: "RESET_FORGET_PASSWORD",

  // Trade Types
  TRADE_FEE_REQUEST: "TRADE_FEE_REQUEST",
  TRADE_FEE_SUCCESS: "TRADE_FEE_SUCCESS",
  TRADE_FEE_FAILURE: "TRADE_FEE_FAILURE",

  // Crypto Summary
  GET_CRYPTO_SUMMARY_REQUEST: "GET_CRYPTO_SUMMARY_REQUEST",
  GET_CRYPTO_SUMMARY_SUCCESS: "GET_CRYPTO_SUMMARY_SUCCESS",
  GET_CRYPTO_SUMMARY_FAILURE: "GET_CRYPTO_SUMMARY_FAILURE",

  // Transaction -> Deposits
  GET_TRANSACTION_DEPOSIT_REQUEST: "GET_TRANSACTION_DEPOSIT_REQUEST",
  GET_TRANSACTION_DEPOSIT_SUCCESS: "GET_TRANSACTION_DEPOSIT_SUCCESS",
  GET_TRANSACTION_DEPOSIT_FAILURE: "GET_TRANSACTION_DEPOSIT_FAILURE",

  // Transaction -> Requests
  GET_TRANSACTION_REQUEST_REQUEST: "GET_TRANSACTION_REQUEST_REQUEST",
  GET_TRANSACTION_REQUEST_SUCCESS: "GET_TRANSACTION_REQUEST_SUCCESS",
  GET_TRANSACTION_REQUEST_FAILURE: "GET_TRANSACTION_REQUEST_FAILURE",

  // Transaction -> Statement
  GET_TRANSACTION_STATEMENT_REQUEST: "GET_TRANSACTION_STATEMENT_REQUEST",
  GET_TRANSACTION_STATEMENT_SUCCESS: "GET_TRANSACTION_STATEMENT_SUCCESS",
  GET_TRANSACTION_STATEMENT_FAILURE: "GET_TRANSACTION_STATEMENT_FAILURE",

  // Transaction -> Withdrawal
  GET_TRANSACTION_WITHDRAWAL_REQUEST: "GET_TRANSACTION_WITHDRAWAL_REQUEST",
  GET_TRANSACTION_WITHDRAWAL_SUCCESS: "GET_TRANSACTION_WITHDRAWAL_SUCCESS",
  GET_TRANSACTION_WITHDRAWAL_FAILURE: "GET_TRANSACTION_WITHDRAWAL_FAILURE",

  // Change password
  POST_CHANGE_PASSWORD_REQUEST: "POST_CHANGE_PASSWORD_REQUEST",
  POST_CHANGE_PASSWORD_SUCCESS: "POST_CHANGE_PASSWORD_SUCCESS",
  POST_CHANGE_PASSWORD_FAILURE: "POST_CHANGE_PASSWORD_FAILURE",

  // User detail
  GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE: "GET_USER_INFO_FAILURE",

  // Get 2FA
  GET_2FA_CODE_REQUEST: "GET_2FA_CODE_REQUEST",
  GET_2FA_CODE_SUCCESS: "GET_2FA_CODE_SUCCESS",
  GET_2FA_CODE_FAILURE: "GET_2FA_CODE_FAILURE",

  // POST ENABLE 2FA
  POST_ENABLE_2FA_CODE_REQUEST: "POST_ENABLE_2FA_CODE_REQUEST",
  POST_ENABLE_2FA_CODE_SUCCESS: "POST_ENABLE_2FA_CODE_SUCCESS",
  POST_ENABLE_2FA_CODE_FAILURE: "POST_ENABLE_2FA_CODE_FAILURE",

  // POST DISABLE 2FA
  POST_DISABLE_2FA_CODE_REQUEST: "POST_DISABLE_2FA_CODE_REQUEST",
  POST_DISABLE_2FA_CODE_SUCCESS: "POST_DISABLE_2FA_CODE_SUCCESS",
  POST_DISABLE_2FA_CODE_FAILURE: "POST_DISABLE_2FA_CODE_FAILURE",

  // POST VERIFY 2FA
  POST_VERIFY_2FA_CODE_REQUEST: "POST_VERIFY_2FA_CODE_REQUEST",
  POST_VERIFY_2FA_CODE_SUCCESS: "POST_VERIFY_2FA_CODE_SUCCESS",
  POST_VERIFY_2FA_CODE_FAILURE: "POST_VERIFY_2FA_CODE_FAILURE",

  // GET EXCHANGE RATE
  GET_EXCHANGE_RATES_REQUEST: "GET_EXCHANGE_RATES_REQUEST",
  GET_EXCHANGE_RATES_SUCCESS: "GET_EXCHANGE_RATES_SUCCESS",
  GET_EXCHANGE_RATES_FAILURE: "GET_EXCHANGE_RATES_FAILURE",

  // GET TICKERS
  GET_TICKER_REQUEST: "GET_TICKER_REQUEST",
  GET_TICKER_SUCCESS: "GET_TICKER_SUCCESS",
  GET_TICKER_FAILURE: "GET_TICKER_FAILURE",

  // GET PRICES
  GET_PRICE_REQUEST: "GET_PRICE_REQUEST",
  GET_PRICE_SUCCESS: "GET_PRICE_SUCCESS",
  GET_PRICE_FAILURE: "GET_PRICE_FAILURE",

  // GET WALLET ADDRESS
  GET_WALLET_ADDRESS_REQUEST: "GET_WALLET_ADDRESS_REQUEST",
  GET_WALLET_ADDRESS_SUCCESS: "GET_WALLET_ADDRESS_SUCCESS",
  GET_WALLET_ADDRESS_FAILURE: "GET_WALLET_ADDRESS_FAILURE",

  // POST DEPOSIT REQUEST
  POST_DEPOSIT_REQUEST_REQUEST: "POST_DEPOSIT_REQUEST_REQUEST",
  POST_DEPOSIT_REQUEST_SUCCESS: "POST_DEPOSIT_REQUEST_SUCCESS",
  POST_DEPOSIT_REQUEST_FAILURE: "POST_DEPOSIT_REQUEST_FAILURE",

  // POST WITHDRAW REQUEST
  POST_WITHDRAW_AMOUNT_REQUEST: "POST_WITHDRAW_AMOUNT_REQUEST",
  POST_WITHDRAW_AMOUNT_SUCCESS: "POST_WITHDRAW_AMOUNT_SUCCESS",
  POST_WITHDRAW_AMOUNT_FAILURE: "POST_WITHDRAW_AMOUNT_FAILURE",

  // POST WITHDRAW OTP REQUEST
  POST_WITHDRAW_OTP_REQUEST: "POST_WITHDRAW_OTP_REQUEST",
  POST_WITHDRAW_OTP_SUCCESS: "POST_WITHDRAW_OTP_SUCCESS",
  POST_WITHDRAW_OTP_FAILURE: "POST_WITHDRAW_OTP_FAILURE",
};
